/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker */

#ifndef _Included_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker
#define _Included_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker
 * Method:    jniConnectEyeXTracker
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_jniConnectEyeXTracker
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_close
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker
 * Method:    startTracking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_startTracking
  (JNIEnv *, jobject);

/*
 * Class:     edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker
 * Method:    stopTracking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_stopTracking
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
