/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread */

#ifndef _Included_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread
#define _Included_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread_MIN_PRIORITY
#define edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread_MIN_PRIORITY 1L
#undef edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread_NORM_PRIORITY
#define edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread_NORM_PRIORITY 5L
#undef edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread_MAX_PRIORITY
#define edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread_MAX_PRIORITY 10L
/*
 * Class:     edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_BackgroundThread
 * Method:    jniBeginMainloop
 * Signature: (Ledu/ysu/itrace/trackers/PCEyeMiniEyeXTracker;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ysu_itrace_trackers_PCEyeMiniEyeXTracker_00024BackgroundThread_jniBeginMainloop
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
